%SKELETON
{% set dataProductNameWithTrims = parameters.dataproduct.split(".")[1] | replace(r/ /g, "-") %}
{% set componentNameWithTrims = parameters.name.split(" ") | reject("equalto", "") | join("-") | lower %}
{% set dataProductMajorVersion = parameters.identifier.split(".")[2] %}

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ parameters.identifier }}
  description: ${{ parameters.description | dump }}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - output-port
    - postgresql
spec:
  type: outputport
  lifecycle: experimental
  owner: ${{ parameters.owner | dump }}
  system: ${{ parameters.dataproduct | dump }}
  domain: ${{ parameters.domain | dump }}
  mesh:
    name: ${{ parameters.name | dump }}
    fullyQualifiedName: ${{ parameters.domainName }} - ${{ parameters.dataproductName }} - version ${{ dataProductMajorVersion }} - ${{ parameters.name }}
    description: ${{ parameters.description | dump }}
    kind: outputport
    infrastructureTemplateId: ${{ values.infrastructureTemplateId }}
    useCaseTemplateId: ${{ values.useCaseTemplateId }}
    platform: PostgreSQL
    technology: PostgreSQL
    outputPortType: PostgreSQL
    dependsOn: []
    tags: {% if parameters.tags | length > 0 %}{% for i in parameters.tags %} 
      - tagFQN: ${{ i }}
        source: Classification
        labelType: Manual
        state: Confirmed{% endfor %}{% else %}[]{% endif %}
    processDescription: ${{ parameters.processDescription | dump }}
    dataContract:
      ontologyname: ${{ parameters.ontologyname }}
    dataSharingAgreement:
      purpose: ${{ parameters.purpose | dump }}
      billing: ${{ parameters.billing | dump }}
      security: ${{ parameters.security | dump }}
      intendedUsage: ${{ parameters.intendedUsage | dump }}
      limitations: ${{ parameters.limitations | dump }}
      lifeCycle: ${{ parameters.lifeCycle | dump }}
      confidentiality: ${{ parameters.confidentiality | dump }}
    specific:
      owner: "${{ parameters.owner }}"
      host: '${{ parameters.host }}'
      port: '${{ parameters.port }}'
      dbname: '${{ parameters.dbname }}'
      user: '${{ parameters.user }}'
      password: '${{ parameters.password }}'
      table: '${{ parameters.table }}'
      schema: '${{ parameters.schema | default("public") }}'
    sampleData: {}
    semanticLinking: []
    consumable: true
    shoppable: true
